---
config:
  theme: 'forest'
---
timeline
    title Timeline for Timothy Mix, American  Revolution Year 1
    section Year 1
        April 1775 : 19 April 1775 “the shot heard ‘round the world”. The battles of Lexington and Concord
        May 1775 : x May 1775 Timothy Mix (1740-1824) enlists in Connecticut (Militia?)
    section Year 2
        January 1776 : Thomas Paine published "Common Sense"
        July 1776 : 4 July 1776 The Declaration of Independence : 1776 Timothy Mix serves with (tbd)
    section Year 3
        Month 1777 : 1777 Timothy Mix serves with (Captain Jonathan Brown’s Co. in the Battalion of Artillery commanded by Col. John Lamb) as a Sergeant
        July 1777 : A Company Muster Roll dated __ July 1777 has remarks “prisoner” (0860.jpg)
        October 1777 : 6 Oct 1777 taken prisoner at the Battle of Fort Montgomery
section Year 4
        Month 1778 : 1778 Timothy Mix serves with (Captain Jonathan Brown’s Co., Colonel John Lamb’s Regiment of Artillery) as a Sergeant
        April 1778 : Timothy Mix is returned around April 1778 from being a prisoner
        September 1778 : 12 Sep 1778 He is promoted from a Sergt. to a 2nd Lieut. on Sepr 12, 1778 in this Compy
    section Year 5
        July 1779 : 16-17 July 1779 The Storming of Stony Point. Timothy Mix serves with (Captain Jonathan Brown’s Co., Colonel John Lamb’s Regiment of Artillery) as a Sergeant then 2nd Lieutenant (his rank is updated several months after perhaps being given a field promotion)
        December 1779 : On command Gen’l Poors Brigade starting December 1779 : Doctor Timothy Mix dies 15 Dec 1779 
    section Year 6
        Month 1780 : 1780 Timothy Mix serves with (Captain Joseph Thomas’ Company in the 2d Regiment of Artillery commanded by Col. John Lamb) as a 2nd Lieutenant
        Month 1780 : On command Gen’l Poors Brigade since December 1779
        August 1780 : On command West Point between February and August 1780
    section Year 7
        Month 1781 : 1781 Timothy Mix serves with (Captain Joseph Thomas’ Company in the 2d Regiment of Artillery commanded by Col. John Lamb) as a 2nd Lieutenant
        October 1781 : Timothy the youngest is named as a British prisoner who was captured from the “privateer schooner Young Cromwell”, captured in October 1781. : Timothy the youngest died on an unknown date between capture and April 1782.
    section Year 8
        Month 1782 : 1782 Timothy Mix serves with (Captain Joseph Thomas’ Company in the 2d Regiment of Artillery commanded by Col. John Lamb)
        February 1782 : Feb 1782 On Command at Springfield starting by February
        September 1782 : 20 September 1782 appointed 1st Lieutenant
    section Year 9+
        Month 1783 : 1783 Timothy Mix serves with (Captain Joseph Thomas’ Company in the 2d Regiment of Artillery commanded by Col. John Lamb)
        September 1783 : 03 September 1783 The signing of the Treaty of Paris marks the official end of the war : 20 Sep 1783 Timothy resigned as 1st Lieut. in Col. Lamb's Artillery 
