timeline
    title Timeline for Timothy Mix
    section French and Indian War
        Year 1755 : Served as Surgeon's Mate
        Year 1757 : Served as Serj. Aug 8-24, 1757. in Capt. Peck's New Haven Company 
        Year 1758 : Service description?
    section American Revolution
        Year 1775 : 19 April 1775 “the shot heard ‘round the world”. The battles of Lexington and Concord : May 1775 Timothy Mix (1740-1824) enlists in Connecticut
        Year 1776 : 4 July 1776 The Declaration of Independence : 1776 Timothy Mix serves with (tbd)
        Year 1777 : 1777 Timothy Mix serves with (Captain Jonathan Brown’s Co. in the Battalion of Artillery commanded by Col. John Lamb) as a Sergeant : A Company Muster Roll dated July 1777 has remarks “prisoner” 0860.jpg : 6 Oct 1777 taken prisoner at the Storming (or Battle) of Fort Montgomery
        Year 1778 : 1778 Timothy Mix serves with (Captain Jonathan Brown’s Co., Colonel John Lamb’s Regiment of Artillery) as a Sergeant : he is returned around April 1778 from being a prisoner : He is promoted from a Sergt. to a 2nd Lieut. on Sepr 12, 1778 in this Compy
        Year 1779 : 1779 Timothy Mix serves with (Captain Jonathan Brown’s Co., Colonel John Lamb’s Regiment of Artillery) as a Sergeant then 2nd Lieutenant (his rank is updated several months after perhaps being given a field promotion) : On command Gen’l Poors Brigade starting December 1779 : Doctor Timothy Mix dies 15 Dec 1779
        Year 1780 : 1780 Timothy Mix serves with (Captain Joseph Thomas’ Company in the 2d Regiment of Artillery commanded by Col. John Lamb) as a 2nd Lieutenant : On command Gen’l Poors Brigade since December 1779 : On command West Point between February and August 1780
        Year 1781 : 1781 Timothy Mix serves with (Captain Joseph Thomas’ Company in the 2d Regiment of Artillery commanded by Col. John Lamb) as a 2nd Lieutenant : Timothy Mix the youngest is named as a British prisoner who was captured from the “privateer schooner Young Cromwell”, captured in October 1781. He died between then and April 1782.
        Year 1782 : 1782 Timothy Mix serves with (Captain Joseph Thomas’ Company in the 2d Regiment of Artillery commanded by Col. John Lamb) : On Command at Springfield starting by February : 20 September 1782 appointed 1st Lieutenant
        Year 1783 : 1783 Timothy Mix serves with (Captain Joseph Thomas’ Company in the 2d Regiment of Artillery commanded by Col. John Lamb) : 03 September 1783 The signing of the Treaty of Paris marks the official end of the war : 20 Sep 1783 resigned as 1st Lieut. in Col. Lamb's Artillery 

%% Notes: 
%% 1757 Militia Company Rolls, https://dn760108.eu.archive.org/0/items/rollsofconnectic09conn/rollsofconnectic09conn.pdf
%% 1755-1757 are in Vol I, Rolls09
%% 1758-1762 are in Vol II, Rolls10
