---
{theme: default}
---
gantt
    title a Gantt chart timeline for Timothy Mix, American Revolution
    dateFormat YYYY-MM-DD
    section 1775    
        The battles of Lexington and Concord     :a1, 1775-04-19, 1d
        Timothy Mix (1740-1824) enlists    :a2, 1775-05-1, 180d
        June 1775    :a3, 1775-06-1, 30d
        July 1775    :a4, 1775-07-1, 31d 
        August 1775    :a5, 1775-08-1, 30d 
        September 1775    :a6, 1775-09-1, 30d          
    section 1776
        Thomas Paine published "Common Sense"   :b1, 1776-01-02, 1d
        The Declaration of Independence   :b2, 1776-07-04, 1d
        Timothy Mix serves with (tbd)     :b3, 1776-01-01, 365d
    section 1777
        Timothy Mix serves as Sergeant     :c1, 1777-01-01, 365d
        Timothy marked as “prisoner” (0860.jpg)   :c2, 1777-06-01, 1d
        taken prisoner at the Battle of Fort Montgomery   :c3, 1777-10-06 ,32w
    section 1778
        Timothy Mix serves as (TBD)     :c1, 1778-01-01, 365d
    section 1779
        Timothy Mix serves as 2nd Lieutenant     :e1, 1779-01-01, 365d
    section 1780
        Timothy Mix serves as 2nd Lieutenant     :f1, 1780-01-01, 365d     
    section 1781
        Timothy Mix serves as 2nd Lieutenant     :g1, 1781-01-01, 100d 
        Timothy Mix serves as 1st Lieutenant (date TBD)    :g2, after g1, 265d
